### Site Settings ###
title               : Lars Schieffer
description         : >-
                      Master's student in computer science at 
                      the Saarland University.
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
remote_theme        : YoussefRaafatNasry/portfolYOU


### Plugins ###
plugins:
  - jemoji
  - jekyll-github-metadata


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Lars Schieffer
  image             : assets/lars-schieffer.jpg
  email             : lars@larsschieffer.de
  xing              : Lars_Schieffer
  linkedin          : larsschieffer
  # github            : larsschieffer


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"